### ISSUE TITLE
Can't use numpy.load with smart open and mmap_mode

### ISSUE THREAD

**Issue by mataney** [piskvorky/smart_open#624]
When trying to use np.load with smart_open and mmap_mode I'm getting an os.fspath TypeError.

```python
>>> import numpy as np
>>> from smart_open import open as sopen
>>> arr = np.array([1,2,3])
>>> fakefile = 'gs://PATHTOFILE'
>>> np.save(sopen(fakefile, 'wb'), arr)
>>> np.load(sopen(fakefile, 'rb'))
array([1, 2, 3])
>>> np.load(sopen(fakefile, 'rb'), mmap_mode='r')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../lib/python3.7/site-packages/numpy/lib/npyio.py", line 438, in load
    return format.open_memmap(file, mode=mmap_mode)
  File ".../lib/python3.7/site-packages/numpy/lib/format.py", line 863, in open_memmap
    with open(os_fspath(filename), 'rb') as fp:
TypeError: expected str, bytes or os.PathLike object, not Reader
```

Versions:
Linux-4.19.0-16-cloud-amd64-x86_64-with-debian-10.9
Python 3.7.3 (default, Jan 22 2021, 20:04:44)
smart_open 3.0.0
numpy 1.20.2

Thanks!

**Comment by piskvorky** [comment]
Does GS even support mmap? I'm very doubtful..

**Comment by ddelange** [comment]
from the traceback, it looks like np.open uses it's own `open` under the hood when passing mmap, and so it expects a path, not an (smart)opened path. I think youd want to monkeypatch builtin `open` in the namespace `numpy.lib.format` with `smart_open.open`, pass your `gs://` path as string to `np.open`, and hope that this `os_fspath` function is happy with your input.

**Comment by ddelange** [comment]
with #599, this is no longer handled by smart_open (and it might actually be fixed by that refactor)
