### ISSUE TITLE
Inconsistent python_requires minimum version

### ISSUE THREAD

**Issue by pressler-vsc** [piskvorky/smart_open#806]
[`python_requires`](https://github.com/piskvorky/smart_open/blob/4aff98ba7085e7cfb91dba9dbe22dca9c1e3e7b5/setup.py#L88) claims `>=3.6`, but should likely be 3.7? This may've been around for a while but the `from __future__ import annotations` in `s3.py` is finally causing an exception upon import:

```shell
$ conda create -n tmp python=3.6
$ conda activate tmp
$ pip install smart_open

$ python --version
Python 3.6.13 :: Anaconda, Inc.

$ conda list smart-open
# packages in environment at /home/vscuser/miniconda3/envs/smartopenbug:
#
# Name                    Version                   Build  Channel
smart-open                7.0.1                    pypi_0    pypi

$ python -c 'import smart_open'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/vscuser/miniconda3/envs/smartopenbug/lib/python3.6/site-packages/smart_open/__init__.py", line 34, in <module>
    from .smart_open_lib import open, parse_uri, smart_open, register_compressor  # noqa: E402
  File "/home/vscuser/miniconda3/envs/smartopenbug/lib/python3.6/site-packages/smart_open/smart_open_lib.py", line 35, in <module>
    from smart_open import doctools
  File "/home/vscuser/miniconda3/envs/smartopenbug/lib/python3.6/site-packages/smart_open/doctools.py", line 21, in <module>
    from . import transport
  File "/home/vscuser/miniconda3/envs/smartopenbug/lib/python3.6/site-packages/smart_open/transport.py", line 104, in <module>
    register_transport("smart_open.s3")
  File "/home/vscuser/miniconda3/envs/smartopenbug/lib/python3.6/site-packages/smart_open/transport.py", line 49, in register_transport
    submodule = importlib.import_module(submodule)
  File "/home/vscuser/miniconda3/envs/smartopenbug/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/vscuser/miniconda3/envs/smartopenbug/lib/python3.6/site-packages/smart_open/s3.py", line 9
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined
```

**Comment by mpenkov** [comment]
Yes, we no longer support Py3.6, as security support ended two years ago. setup.py is out of date.

**Comment by mpenkov** [comment]
are you interested in making a PR?

**Comment by pressler-vsc** [comment]
That's very reasonable; I figured as much.  I've attempted a PR and hopefully didn't butcher the PR template/process.
